spring:
  application:
    name: trello
  data:
    mongodb:
      database: ${spring.application.name}
      host: mongo
  security:
    user:
      name: ${spring.application.name}
      password: ${spring.application.name}
server:
  servlet:
    context-path: /${spring.application.name}
  port: 8098
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost

